name: Deploy MarkBind Site
on:
  push:
    branches: main
jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy to GitHub Pages
        uses: MarkBind/markbind-action@release/v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          baseUrl: '/markbind_actions_test'